deployments:
  default_deployment: local_model
  enabled_deployments:
      - localmodel
database:
  url: postgresql+psycopg2://postgres:postgres@db:5432
redis:
  url: redis://:redis@redis:6379
tools:
  hybrid_web_search:
    # List of web search tool names, eg: google_web_search, tavily_web_search
    enabled_web_searches:
      - tavily_web_search
  python_interpreter:
    url: http://terrarium:8080
  slack:
    user_scopes:
      - search:read
feature_flags:
  # Experimental features
  use_agents_view: false
  # Community features
  use_community_features: true
auth:
  enabled_auth:
    - basic
    - google_oauth
    - oidc
  backend_hostname: http://localhost:8000
  frontend_hostname: http://localhost:4000
logger:
  strategy: structlog
  renderer: console
  level: info
