"""

Revision ID: 2a798d35b3e9
Revises: bfb08a34922a
Create Date: 2024-11-17 17:39:21.949998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.database_models.seeders.deplyments_models_seed import deployments_models_seed, delete_default_models   


# revision identifiers, used by Alembic.
revision: str = '2a798d35b3e9'
down_revision: Union[str, None] = 'bfb08a34922a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    deployments_models_seed(op)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    delete_default_models(op)
    # ### end Alembic commands ###
