"""removed user-id from study added status

Revision ID: 4e3eaec553bf
Revises: 11bb482f1553
Create Date: 2024-11-06 04:49:05.893555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3eaec553bf'
down_revision: Union[str, None] = '11bb482f1553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('is_being_added', sa.Boolean(), nullable=False))
    op.drop_constraint('_study_name_user_uc', 'studies', type_='unique')
    op.create_unique_constraint('_study_name_uc', 'studies', ['name'])
    op.drop_constraint('studies_user_id_fkey', 'studies', type_='foreignkey')
    op.drop_column('studies', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('studies_user_id_fkey', 'studies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('_study_name_uc', 'studies', type_='unique')
    op.create_unique_constraint('_study_name_user_uc', 'studies', ['name', 'user_id'])
    op.drop_column('studies', 'is_being_added')
    # ### end Alembic commands ###
